/**
 * The block.
 *
 * The PHPUnit suite already proves the render callback returns what the
 * shortcode returns, that neither is implemented in terms of the other, and
 * that rendering never increments a count, so repeating any of that here would
 * buy nothing. What only a browser can answer is whether the *built* JavaScript
 * works: `build/` is generated by bin/build and is not in the repository, so
 * every assertion below is also an assertion that the build ran and produced
 * something a browser can load.
 *
 * Two things are worth a browser, and nothing else here is:
 *
 * * the editor script loads and registers the block -- a broken build, a
 *   missing dependency in index.asset.php or a bad block.json all show up here
 *   and nowhere else;
 * * a count rendered from a block reaches a reader, which exercises the block
 *   comment saved into post_content against the real block parser.
 *
 * The count is read from a *second* post throughout, never from the post being
 * looked at. Visiting a post counts a view of it, so a block reading the host
 * post's own count would be asserting against a number the visit itself moved.
 */

const { test, expect } = require( '@wordpress/e2e-test-utils-playwright' );
const {
	resetOptions,
	setViews,
	uniqueTitle,
	views,
} = require( './helpers.js' );

/** The block this plugin registers. */
const VIEWS_BLOCK = 'wp-postviews/views';

test.describe( 'The block', () => {
	let source;

	test.beforeEach( async ( { requestUtils } ) => {
		resetOptions();

		source = await requestUtils.createPost( {
			title: uniqueTitle( 'Counted elsewhere' ),
			content: 'A post nobody visits, holding a count to render.',
			status: 'publish',
		} );
	} );

	test.describe( 'in the editor', () => {
		test( 'the block is registered, under the prefixed name', async ( {
			admin,
			editor,
			page,
		} ) => {
			await admin.createNewPost();
			await editor.canvas.locator( 'body' ).waitFor();

			const names = await page.evaluate( () =>
				window.wp.blocks.getBlockTypes().map( ( type ) => type.name ),
			);

			// If the build did not run, or index.asset.php named a dependency
			// that does not exist, the editor script never executes and the
			// name is not here -- which is the failure this whole file exists
			// for.
			expect( names ).toContain( VIEWS_BLOCK );

			// The prefix is not decoration: a block name is written into
			// post_content and lives there for the life of the post.
			expect( names ).not.toContain( 'postviews/views' );
		} );

		test( 'the preview shows the count, and does not add to it', async ( {
			admin,
			editor,
		} ) => {
			setViews( source.id, 321 );

			await admin.createNewPost();
			await editor.insertBlock( {
				name: VIEWS_BLOCK,
				attributes: { id: source.id },
			} );

			// The preview is core's ServerSideRender, which posts the
			// attributes to /wp/v2/block-renderer/ and draws what the front end
			// would draw. Seeing the count here is what proves the block earns
			// no REST route of its own.
			await expect(
				editor.canvas.getByText( '321 views' ),
			).toBeVisible();

			// An author arranging a post re-renders the preview on every
			// keystroke in the id field. If that ever counted, the number a
			// block is there to report would be mostly the author looking at
			// it, and nothing in the stored figure would say so.
			expect( views( source.id ) ).toBe( 321 );
		} );
	} );

	test.describe( 'on the front end', () => {
		test( 'a post holding the block renders the count', async ( {
			page,
			requestUtils,
		} ) => {
			setViews( source.id, 654 );

			const post = await requestUtils.createPost( {
				title: uniqueTitle( 'A count in a block' ),
				content: `<!-- wp:${ VIEWS_BLOCK } {"id":${ source.id }} /-->`,
				status: 'publish',
			} );

			await page.goto( post.link );

			await expect( page.locator( '.entry-content' ) ).toContainText(
				'654 views',
			);
		} );
	} );
} );
